# Generated by Django 3.0.3 on 2020-02-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_catname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='CatName',
            new_name='cat_name',
        ),
    ]
