# Generated by Django 3.0.3 on 2020-02-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20200219_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Post')),
            ],
        ),
    ]
