# Generated by Django 3.0.3 on 2020-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='user_name',
            field=models.CharField(default='osama', max_length=25),
            preserve_default=False,
        ),
    ]
