# Generated by Django 3.0.3 on 2020-02-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_reaction_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Posts.Category')),
            ],
        ),
    ]
