# Generated by Django 3.0.3 on 2020-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='post_name',
            field=models.ManyToManyField(db_table='PostTags', to='Posts.Post'),
        ),
    ]
