# Generated by Django 3.0.3 on 2020-02-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_post_thumbnail'),
        ('Posts', '0012_tags_post_name'),
    ]

    operations = [
    ]
