# Generated by Django 3.0.3 on 2020-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_merge_20200221_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='post_name',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_name',
            field=models.ManyToManyField(db_table='PostTags', to='Posts.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=20),
        ),
    ]
