# Generated by Django 3.0.3 on 2020-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0017_auto_20200222_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='react',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('none', 'none')], default='none', max_length=7),
        ),
    ]
