# Generated by Django 3.0.3 on 2020-02-23 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0018_auto_20200223_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
