# Generated by Django 3.0.3 on 2020-02-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0019_auto_20200223_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='cat_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Posts.Category'),
        ),
    ]
