# Generated by Django 3.0.3 on 2020-02-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0019_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Comments'),
        ),
    ]
