# Generated by Django 3.0.3 on 2020-02-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0020_auto_20200223_0156'),
        ('Posts', '0021_badword'),
    ]

    operations = [
    ]
