# Generated by Django 3.0.3 on 2020-02-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0022_merge_20200224_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Posts.Category'),
        ),
    ]
