# Generated by Django 3.0.3 on 2020-02-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourBlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
